### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-input-s3#13]
Currently every "interval (60 seconds)" input only downloads 1 file and processes.
A bucket with thousands of files will take thousands of minutes (1 min per file) to ingest.
If there can be a bulk/batch option to download X files and process then can hopefully can ingest bucket with lots of files faster.
Also specifying -w # doesn't appear to improve by utilizing threads for multiple items either.
So only way to improve this would be to have multiples of the same input which could potentially cause conflicts? (maybe specifying same sincedb might allow them to work together nicely?)

**Comment by ph** [comment]
This is a needed improvement, having multiple input using the same `sincedb` isn't an option for now. Since this part of the code isn't threadsafe. One way to workaround it is to use multiple inputs with different prefix and of course different sincedb_path.

**Comment by cdenneen** [comment]
@ph different prefix? Can you explain?

**Comment by DanielRedOak** [comment]
See https://github.com/logstash-plugins/logstash-input-s3/pull/25

**Comment by cdenneen** [comment]
@ph @DanielRedOak I'm running latest logstash 5 and have 7 s3 inputs with different prefixes to parse each month of this year individually but the inputs are taking forever to load 30 days worth of data.
Obviously it's a lot of data but there needs to be something to speed this up. 
Whether that's having more input threads than cores so they can batch up quicker, much much smaller interval so it cycles back faster, something... my 4 core box for the most part is at least 80-90% idle so it's definitely not processing to it's fully potential.
If you need any info for config, api stats, etc I'd be happy to share and willing to test any config changes in order to improve performance considerably here.
