### ISSUE TITLE
Fail gracefully when S3 object disappears

### ISSUE THREAD

**Issue by danielkasen** [logstash-plugins/logstash-input-s3#133]
Currently I have multiple logstash instances pulling form the same place and in order to avoid duplicates in ES I have decided to simpley delete the object once it is fetched. Obviously this creates race conditions where client A deletes the object while client B is downloading it and you wind up with this Error and the s3 input plugin restarting:

>  plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:s3-cloudtrail-logs
  Plugin: <LogStash::Inputs::S3 bucket=>"prd-elasticsearch-logs-processing", prefix=>"cloudtrail", exclude_pattern=>"CloudTrail-Digest", delete=>true, region=>"ap-southeast-1", interval=>30, sincedb_path=>"/storage/awslogs/s3_sincedb", add_field=>{"class"=>"cloudtrail"}, codec=><LogStash::Codecs::CloudTrail id=>"c1f78213-a41f-4bd5-a32e-ebf888969c08", enable_metric=>true, charset=>"UTF-8">, id=>"b1f34a33085ed7e264f30d348eb452cb288bcc263b41e6142eefc5eb060d4122", enable_metric=>true, temporary_directory=>"/tmp/logstash">
  Error: The specified key does not exist.
  Exception: Aws::S3::Errors::NoSuchKey
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/seahorse/client/request.rb:70:in `send_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:207:in `block in define_operation_methods'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/request.rb:24:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/operations.rb:41:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:373:in `block in download_remote_file'
org/jruby/RubyIO.java:1156:in `open'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:371:in `download_remote_file'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:348:in `process_log'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:152:in `block in process_files'
org/jruby/RubyArray.java:1734:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:147:in `process_files'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:103:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-3.2.0/lib/logstash/inputs/s3.rb:102:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509:in `block in start_input'

It would be nice if we could fail gracefully and clean up the attempted download otherwise this simply fills up my tmp directory with half downloaded files. Ideally there would be a way to share a since_db file across all nodes but that doesn't exist at this time.

**Comment by skkhajamohiddin** [comment]
any one work around this ??

**Comment by robbavey** [comment]
This should have been fixed by #144

**Comment by ivanboykoatitv** [comment]
I don't think it was fixed.

We are using plugin version `3.3.2` according to `logstash-input-s3.gemspec`.
And we stilt get the same plugin crashes.
The worst part is that plugin leaves lots of files in `/var/lib/logstash/logstash`, which is our (temporary_directory)[https://www.elastic.co/guide/en/logstash/6.8/plugins-inputs-s3.html#plugins-inputs-s3-temporary_directory]
