### ISSUE TITLE
S3 directory handling

### ISSUE THREAD

**Issue by wiibaa** [logstash-plugins/logstash-input-s3#17]
_From [LOGSTASH-1548](https://logstash.jira.com/browse/LOGSTASH-1548)_

>Can the s3 input plugin be upgraded to search specific folders?
>For example, in the file input you can define a glob to search via.
>like /var/log/apache2/access*
>How would it be possible to do the same thing for s3 input?
>Also be handy to define in the s3 output the same thing. So you could put the files into a specific >folder structure you define.

@ph Is it not what the prefix config is doing ?

**Comment by ph** [comment]
You are right, the prefix is the way to do it with the S3 API, if you do `prefix => '/var/log/apache2/access'` it will match any keys with that specific pattern. I dont think we can implement globbing support without doing it locally, If I remember correctly valid S3 keys can contains wildcards  '*'

**Comment by wiibaa** [comment]
Ok for me, enough info to close the issue
