### ISSUE TITLE
document example of exclude_pattern usage

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-s3#170]
the documentation doesn't contain an example of how `exclude_pattern` can be used, which would be useful for users

**Comment by psanz-estc** [comment]
hey @jsvd, we could use some easy example as:

`"exclude_pattern" => "\/2019\/03\/"`

That should exclude all the logs containing "/2019/03/" in the path

**Comment by karenzone** [comment]
@psanz-estc  Thank you for providing an example. Very helpful. <3

**Comment by eojeda76** [comment]
is it possible to exclude multiple patterns? For example, exclude all the logs containing the following in the path:
/2019/03/
/2019/02/
/2020/02/
/2020/03/

**Comment by alvarofernandezavalos** [comment]
> is it possible to exclude multiple patterns? For example, exclude all the logs containing the following in the path: /2019/03/ /2019/02/ /2020/02/ /2020/03/

Did you found a solution?
