### ISSUE TITLE
Unable to ingest files restored from Glacier

### ISSUE THREAD

**Issue by magical-travvo** [logstash-plugins/logstash-input-s3#199]
When trying to ingest files from S3 that have been temporarily restored from Glacier, they are ignored by this input, as files are excluded based on being in the "Glacier" storage class.

Restored files still remain in a "Glacier" storage class, but include additional metadata indicating that they are temporarily available.  We regularly archive data processed by Logstash to S3 using the logstash-s3-output plugin, and it would be helpful to be able to easily reingest that data once a restore has been completed.

- Version: 6.8.3
- Operating System: CentOS 7
- Steps to Reproduce: Restore file from Glacier, try to restore

**Comment by magical-travvo** [comment]
I've raised https://github.com/logstash-plugins/logstash-input-s3/pull/197 to address the issue.
I'm not sure why the builds are failing.  The tests all pass locally.

**Comment by kares** [comment]
failures are failing due a new major (2.0) of the devutils gem. 
we'll be addressing the issue shortly (on master) ... you should be able to rebase afterwards.

**Comment by kares** [comment]
fix delivered at https://github.com/logstash-plugins/logstash-input-s3/pull/197 and available since 3.5.0
