### ISSUE TITLE
inputs/s3.rb: Keep attempting and failing to parse the same gz file if it's corrupted

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-s3#2]
Moved from https://github.com/elasticsearch/logstash/issues/2090

I'm using logstash v1.4.2. S3 input crashes if a bucket contains a zero-byte gz file. (throwing an error "Error: not in gzip format".) Then, logstash will retry indefinitely since sincedb is not updated.

I've made a change in `list_new` to skip empty S3 objects (attached code below) to address this particular issue but it may be a good idea to have more robust error handling.

``` ruby
  private
  def list_new(since=nil)

    if since.nil?
      since = Time.new(0)
    end

    objects = {}
    @s3bucket.objects.with_prefix(@prefix).each do |log|
      # original code in v1.4.2
      # if log.last_modified > since
      if log.last_modified > since && log.content_size > 0
        objects[log.key] = log.last_modified
      end
    end

    return sorted_objects = objects.keys.sort {|a,b| objects[a] <=> objects[b]}

  end # def list_new
```

**Comment by jsvd** [comment]
list_new has since changed to [list_new_files](https://github.com/logstash-plugins/logstash-input-s3/blob/master/lib/logstash/inputs/s3.rb#L106-L120) and it seems this size check is gone.

@ph can you check if this should be added again?

**Comment by ph** [comment]
Yes it should I will merge this.

**Comment by fritzhardy** [comment]
This is still happening with 3.1.2 under logstash-5.2.2.  I can confirm that https://github.com/logstash-plugins/logstash-input-s3/issues/81 fixes the issue.

**Comment by watollop** [comment]
Any news?

**Comment by solshark** [comment]
Relevant for me as well, any news?

**Comment by jsvd** [comment]
[version 3.1.9 has been published](https://rubygems.org/gems/logstash-input-s3/versions/3.1.9) with the support for ignoring 0 sized gzip files
