### ISSUE TITLE
using fine grained service account IAM roles in EKS

### ISSUE THREAD

**Issue by chelomontilla** [logstash-plugins/logstash-input-s3#207]
Hi,
I'm using [service account iam roles](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) in amazon EKS, but I'm not able to get logstash s3 working using an IAM role.

I can see the environment variables in the pod:
- AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token 

- AWS_ROLE_ARN: arn:aws:iam::0123456789:role/logstash-cloudfront

The input config:
```
input {
      s3 {
        role_arn => "${AWS_ROLE_ARN}"
        bucket => "logs-cloudfront"
        prefix => "staging"
        region => "us-west-1"
      }
}
```
Is there anyway for the plugin to read the identity toke file?
Thanks in advance

**Comment by Chaosmonkeys** [comment]
Any updates?
