### ISSUE TITLE
Error: undefined method `start_with?

### ISSUE THREAD

**Issue by jmreicha** [logstash-plugins/logstash-input-s3#27]
Running Logstash 1.5.0.RC2 and getting the following error message:

```
A plugin had an unrecoverable error. Will restart this plugin.
Error: undefined method `start_with? for nil:NilClass {:level=>:error}
```

Here is the relevant part of my current config.

```
input
s3 {
        bucket => "my-s3-bucket"
        access_key_id => "XXX"
        secret_access_key => "XXX"
        sincedb_path => "/data/logstash/.sincedb-logstash"
        prefix => "path/to/logs"
        type => "cloudtrail"
        codec => "json"
    }

output {
    elasticsearch { cluster => "elasaticsearch" }
}
```

I tested with the `stdout` output and things seemed to work okay.  I tested this config with no codec defined and it pulled logs in but it only created one entry in ES.

Not sure if that means anything or not.

**Comment by ph** [comment]
I've found the issue, the event object did not contains a `message` field and metadata check would make this plugin crash. I've created a PR that check if the field actually exist before doing anything.

**Comment by ph** [comment]
Fixed in the latest version of the plugin.
