### ISSUE TITLE
Plugin fails if it tries to ingest a binary file

### ISSUE THREAD

**Issue by netoneko** [logstash-plugins/logstash-input-s3#31]
Here is the log (the source of the problem was some PNG file in my bucket):

```
2015-04-21T08:03:18.310519241Z {:timestamp=>"2015-04-21T08:03:18.310000+0000", 
:message=>"A plugin had an unrecoverable error. Will restart this plugin.
Plugin: <LogStash::Inputs::S3>[...]
Error: invalid byte sequence in UTF-8", :level=>:error}
```

Maybe it should be wrapped in `begin/rescue` block so the whole plugin won't crash?

**Comment by shuwada** [comment]
Hi, I had the same issue with a corrupted gzip file. Just opened a PR to address it.
