### ISSUE TITLE
OOM Error with logstash s3 input

### ISSUE THREAD

**Issue by vanga** [logstash-plugins/logstash-input-s3#34]
I am trying to index 4 months of logs from multiple buckets. I have logstash and elasticsearch running on a single m3.xlarge(16 GB RAM) instance.
Logstash version: 1.5.0-rc3
Elasticsearch version: 1.5.2 
ArchLinux

After running for some time logstash or elasticsearch would get killed by OOM Killer, If I restart logstash , same thing will happen in few minutes. 
If I reboot the machine, problem won't be there. Memory usage is constant around 70% (50% is for ES Heap)

I have made some observation that /tmp/logstash will be filled up with lot of files, I think s3 input isn't deleting the files after its done with indexing, and it also seems to download files from S3 as soon as it can, irrespective of how fast it is indexing. Rebooting would delete these files, I guess that's why I was able to get logstash back up running after rebooting. I am not sure what temp file got to do with RAM, may be s3 input plugin is trying to load all those files into RAM?

logstash config
https://gist.github.com/vanga/74bc60e88d7e1022b53d
OOM error
https://gist.github.com/vanga/b499b428d8071a72bc79

**Comment by vanga** [comment]
I just checked few more things, cat /proc/meminfo
shows `Cached: 4944212` which is almost same as the size of the temporary files in /tmp/logstash. 
Seems like kernel is not able to get this memory back when needed.

**Comment by ph** [comment]
This look similar to the other OOM bug we had with the AWS plugins in https://github.com/logstash-plugins/logstash-input-sqs/issues/5. I'll check if the issue is related or not and apply the SQS workaround.

**Comment by ph** [comment]
I have fixed the temporary file in this PR. https://github.com/logstash-plugins/logstash-input-s3/pull/36

Also I am making sure the temporary directory exist before writing to it in https://github.com/logstash-plugins/logstash-input-s3/pull/35

**Comment by vanga** [comment]
thanks @ph .
btw, if I delete the old temp files, its clearing up the cached memory and gives some free RAM space. Kernel can't take back this memory or stopping logstash wouldn't clear this memory, I thought only System reboot (which would clear the temp files) would clear this memory.

**Comment by enisinanaj** [comment]
I see this is very old but I'm having the same issue with Logstash 7.6.1 and Elastic 7.6.1
