### ISSUE TITLE
Add ZIP support on s3 input

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-s3#38]
(This issue was originally filed by @pagefaulted at https://github.com/elastic/logstash/issues/1759)

---

Add ZIP support on s3 input

My use case is the ability to process AWS billing logs

**Comment by SleeperSmith** [comment]
Any update?

**Comment by moshe-sa** [comment]
Any update?

**Comment by jordansissel** [comment]
No update at this time.
