### ISSUE TITLE
Error: AWS::S3::Errors::Forbidden 

### ISSUE THREAD

**Issue by maaand** [logstash-plugins/logstash-input-s3#44]
I get the following forbidden error, with input filter configured for aws s3
```
Plugin: <LogStash::Inputs::S3 add_field=>{"kitch_blog"=>"loadbalancer"}, bucket=>"com.xxxxx", access_key_id=>"xxxxxx", secret_access_key=>"xxxxx", prefix=>"AWSLogs/766254664790/elasticloadbalancing/us-east-1/", type=>"apache-access", sincedb_path=>"/etc/logstash/sincedb/", region=>"us-east-1", temporary_directory=>"/tmp/logstash">
  Error: AWS::S3::Errors::Forbidden {:level=>:error}
```

I've uploaded the debug mode output here: 
https://gist.githubusercontent.com/maaand/92e0d8dcc24210eeb191/raw/6e88ab1098a2431b93839d51a13d6c72affe286e/gistfile1.txt

**Comment by maaand** [comment]
```
input {
  s3 { 
    add_field => {"kitch_blog" => "loadbalancer"}
    bucket => "com.xxxxxx"
    access_key_id => "xxxxxx"
    secret_access_key => "xxxxxx"
    prefix => "AWSLogs/766254664790/elasticloadbalancing/us-east-1/"
    type => "apache-access"
    sincedb_path => "/etc/logstash/sincedb/"
  }
}

filter {
  if [type] == "apache-acess" {
    grok { 
      match => { 
        "message" => "%{COMBINEDAPACHELOG}"  
      }
    }
  }
}


output {
       stdout {
              codec => rubydebug 
       }       
}
```

my logfilter conf file, 
logstash version - 1.5.0

**Comment by ph** [comment]
@maaand you have access to read the bucket with the credentials?

**Comment by ph** [comment]
`AWS::S3::Errors::Forbidden`, is normaly related to a problem with the permissions

**Comment by maaand** [comment]
I do.. I checked with s3cmd and also, if you check the debug logs, 
logstash is able to identify the logfile on S3. 
But something goes wrong during fetching/process etc..

```
S3 input: Found key {:key=>"AWSLogs/766254664790/elasticloadbalancing/us-east-1/2015/05/07/766254664790_elasticloadbalancing_us-east-1_xxxxxxx_20150507T0015Z_54.210.15
9.245_9gncgtxa.log", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"110", :method=>"list_new_files"}
```

**Comment by ph** [comment]
So it can read the keys in the bucket but cannot download them?
With the same credentials you can download the problematic file (outside of logtash)?

**Comment by maaand** [comment]
@ph, good point, my aws key doesnt have rights to *get* objects from S3.. closing this issue.
