### ISSUE TITLE
Enhancement Request - Use aws-mixin to enable support for IAM roles

### ISSUE THREAD

**Issue by davidski** [logstash-plugins/logstash-input-s3#5]
Would :heart: X :100:  to have this plugin updated to use the existing logstash-aws-mixin and support IAM roles for authenticating to S3. The use of hard coded credentials (or environment variables) is a real throwback and not consistent with how Things Are Done(tm) on AWS these days. Proper instance role support would be a huge win!

**Comment by ph** [comment]
#1 was merge a few weeks ago.
