### ISSUE TITLE
Error: no time information in \"\"

### ISSUE THREAD

**Issue by tuukkamustonen** [logstash-plugins/logstash-input-s3#64]
Suddenly, I'm getting following error in loop:

    {:timestamp=>"2015-11-16T10:52:24.320000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 bucket=>\"fs-csm-dev\", type=>\"elb\", prefix=>\"access-logs/\", region=>\"eu-west-1\", delete=>true, interval=>60, debug=>false, codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, use_ssl=>true, temporary_directory=>\"/var/lib/logstash/logstash\">\n  Error: no time information in \"\"", :level=>:error}

I am not out of disk space. The directory is:

    $ ls -la /var/lib/logstash/logstash/
    total 8
    drwxr-xr-x 2 logstash logstash 4096 Nov 16 10:55 .
    drwxrwxr-x 4 logstash logstash 4096 Oct  6 07:24 ..

Running logstash 1.5.5.

**Comment by tuukkamustonen** [comment]
I will, just need to first study how to update the plugin...

**Comment by ph** [comment]
I've released the plugin for Logstash 2.0, I didn't backport the fix for 1.5.X
If you are running 2.0, its only a matter of doing bin/plugin update logstash-input-s3

PR https://github.com/logstash-plugins/logstash-input-s3/pull/67

**Comment by tuukkamustonen** [comment]
Tried to upgrade to logstash 2.0.0 and to test it, but I'm running into https://github.com/elastic/logstash/issues/4141

Couldn't find my way around that, I tried to workaround the problem by following https://github.com/elastic/logstash/issues/4141#issuecomment-155412581 but maybe I didn't edit the right places...

I will test it again after 2.0.1 (with fix for concurrent-ruby issue) is released...

**Comment by tuukkamustonen** [comment]
I upgraded to logstash 2.1 today (that comes with the latest 2.0.3 of the plugin) and I am not seeing the error anymore. Instead, I'm now seeing https://github.com/logstash-plugins/logstash-input-s3/issues/59 :)

Anyway, I assume the fix worked so closing this. Thanks!
