### ISSUE TITLE
Slow process Cloudtrail log from S3

### ISSUE THREAD

**Issue by thinhluu** [logstash-plugins/logstash-input-s3#75]
input {
  s3 {
    bucket => "BUCKETNAME"
    delete => true
    interval => 60
    prefix => "AWSLogs/"
    region => "us-west-2"
    codec => "cloudtrail"
    type => "cloudtrail"
  }
}

output {
  stdout { codec => rubydebug }
}

{:timestamp=>"2016-02-26T19:26:17.580000+0000", :message=>"S3 input: Download remote file", :remote_key=>"AWSLogs/AWSAccountID/CloudTrail/us-west-2/2016/02/26/AWSAccountID_CloudTrail_us-west-2_20160226T0800Z_g8AAxJTg73yheICE.json.gz", :local_filename=>"/tmp/logstash/AWSAccountID_CloudTrail_us-west-2_20160226T0800Z_g8AAxJTg73yheICE.json.gz", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"344", :method=>"download_remote_file"}
{:timestamp=>"2016-02-26T19:26:19.262000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:24.266000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:29.267000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:34.270000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:39.271000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:44.271000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:49.272000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:54.272000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
{:timestamp=>"2016-02-26T19:26:59.272000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}

strace -p 3203
Process 3203 attached
futex(0x7fc50e1bd9d0, FUTEX_WAIT, 3218, NULL^CProcess 3203 detached
 <detached ...>

strace -p 3218
futex(0x7fc50800b354, FUTEX_WAIT_BITSET_PRIVATE, 1, {5392, 782048749}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fc50800b328, FUTEX_WAKE_PRIVATE, 1) = 0
gettimeofday({1456515307, 329336}, NULL) = 0
gettimeofday({1456515307, 329479}, NULL) = 0
gettimeofday({1456515307, 329604}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {5392, 782924458}) = 0
futex(0x7fc50800b354, FUTEX_WAIT_BITSET_PRIVATE, 1, {5392, 982924458}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fc50800b328, FUTEX_WAKE_PRIVATE, 1) = 0
gettimeofday({1456515307, 530201}, NULL) = 0
gettimeofday({1456515307, 530347}, NULL) = 0
gettimeofday({1456515307, 530478}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {5392, 983801768}) = 0
futex(0x7fc50800b354, FUTEX_WAIT_BITSET_PRIVATE, 1, {5393, 183801768}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fc50800b328, FUTEX_WAKE_PRIVATE, 1) = 0
gettimeofday({1456515307, 731088}, NULL) = 0
gettimeofday({1456515307, 731234}, NULL) = 0
gettimeofday({1456515307, 731363}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {5393, 184683466}) = 0

**Comment by ph** [comment]
@thinhluu can we get a bit of details about the environment?

Logstash version?
S3 input version (You can get that by running this command `bin/plugin --verbose input-s3`)
The size of the `AWSLogs/AWSAccountID/CloudTrail/us-west-2/2016/02/26/AWSAccountID_CloudTrail_us-west-2_20160226T0800Z_g8AAxJTg73yheICE.json.gz`
Number of files in the bucket?

**Comment by ph** [comment]
Not sure if the download timeout and the exception is not correctly raised?

Is the machine processing the logs is also on AWS?

**Comment by thinhluu** [comment]
/opt/logstash/bin/logstash --version
logstash 2.2.2

/opt/logstash/bin/plugin list --verbose | grep s3
logstash-input-s3 (2.0.4)

There are about 10 files, around 200 KB each.

Standard Ubuntu Server 14.04 LTS (HVM), running in AWS, same region. File was downloaded quickly but keep looping for a long time.

{:timestamp=>"2016-02-26T20:19:53.383000+0000", :message=>"S3 input: Download remote file"...
{:timestamp=>"2016-02-26T20:19:58.316000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}

...

{:timestamp=>"2016-02-26T20:42:13.662000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"
{:timestamp=>"2016-02-26T20:42:22.807000+0000", --- start processing the file


Thanks,
Thinh
