### ISSUE TITLE
Missing S3 Asia Pacific (Seoul) Region "ap-northeast-2"

### ISSUE THREAD

**Issue by joh9970** [logstash-plugins/logstash-input-s3#77]
Region configuration for ap-northeast-2 returns an error:

$ /opt/logstash/bin/logstash -f logstash-s3-test.conf --configtest
Invalid setting for s3 input plugin:

  input {
    s3 {
      # This setting must be a ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"]
      # Expected one of ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"], got ["ap-northeast-2"]
      region => "ap-northeast-2"
      ...
    }
  } {:level=>:error}

$ /opt/logstash/bin/logstash --version
logstash 2.2.2
$ /opt/logstash/bin/plugin list --verbose | grep input-s3
logstash-input-s3 (2.0.4)
$

**Comment by vanga** [comment]
@ghost can you please tell me how you resolved this issue? was this fixed by a new version of logstash or did you do something that resolved this?

Thanks.
